linters-settings:
  errcheck:
    check-type-assertions: true
  forbidigo:
    forbid:
      - '^fmt\.Print'
      - '^log\.'
      - '^print$'
      - '^println$'
      - '^panic$'
  godox:
    # TODO, OPT, etc. comments are fine to commit. Use FIXME comments for
    # temporary hacks, and use godox to prevent committing them.
    keywords: [FIXME]
  varnamelen:
    ignore-decls:
      - T any
      - i int
      - wg sync.WaitGroup
linters:
  enable-all: true
  disable:
    - copyloopvar       # only valid for go v1.22 and above
    - cyclop            # covered by gocyclo
    - depguard          # unnecessary for small libraries
    - execinquery       # deprecated in golangci v1.58 
    - exportloopref     # deprecated in golangci v1.60.2
    - funlen            # rely on code review to limit function length
    - gocognit          # dubious "cognitive overhead" quantification
    - gofumpt           # prefer standard gofmt
    - goimports         # rely on gci instead
    - gomnd             # deprecated in golangci v1.58 in favor of mnd
    - mnd               # some unnamed constants are okay
    - intrange          # only valid for go v1.22 and above
    - ireturn           # "accept interfaces, return structs" isn't ironclad
    - lll               # don't want hard limits for line length
    - maintidx          # covered by gocyclo
    - nlreturn          # generous whitespace violates house style
    - testpackage       # internal tests are fine
    - wrapcheck         # don't _always_ need to wrap errors
    - wsl               # generous whitespace violates house style
    - nonamedreturns    # named returns help document return types
issues:
  exclude-dirs-use-default: false
  exclude:
    # Don't ban use of fmt.Errorf to create new errors, but the remaining
    # checks from err113 are useful.
    - "do not define dynamic errors.*"
  exclude-rules:
    # We need to init a global in-mem HTTP server for testable examples.
    - path: examples_test.go
      linters: [gocritic, gochecknoglobals, gosec, exhaustruct]
